### ISSUE TITLE
Loading V14 is 10x slower

### ISSUE THREAD

**Issue by chevdor** [paritytech/frame-metadata#25]
I am looging this issue to make sure we can track it down.
When loading V14 vs V13 in `subwasm`, I see a 10 folds increase for V14:

- `subwasm info data/runtime_v13.wasm  0.03s user 0.01s system 96% cpu 0.043 total`
- `subwasm info data/runtime_v14.wasm  0.33s user 0.07s system 99% cpu 0.401 total`

NOTE: `subwasm` is still using rc1 as loading V14 with rc2 is failing (I may miss another fix to make it work).

**Comment by ascjones** [comment]
I would expect it to be somewhat slower since it is decoding more data (the entire type hierarchy). An order of magnitude does seem like a lot though.

**Comment by chevdor** [comment]
Closing since this "issue" is non critical and expected.
