### ISSUE TITLE
Adding Metadata v8-11?

### ISSUE THREAD

**Issue by insipx** [paritytech/frame-metadata#27]
I've got metadata versions v8-v11 [here](https://github.com/paritytech/desub/tree/master/substrate-metadata-versions) and recently converted them to use what i could from `frame-metadata`. I think it would now be pretty easy for me to make a PR to this repo and add those metadata versions if it is wanted/needed. I believe V8 to be the first metadata version that Kusama uses

**Comment by ascjones** [comment]
Yeah I think that would be super useful for historic data. Although we may want to consider how we can reduce the number of features as we have a feature per version currently, Maybe we could hide all historical ones behind a single feature.
